name: segment_1

pca:
  n_components: 3
  columns:
  - col1
  - col2
  - col3

kmeans:
  k: 10
  metric: distortion

image:
  pca: image/3d_plot.png
  kmeans: image/elbow.png
  clusters: image/cluster.png