raw_data: 
  path: data/raw/marketing_campaign.csv

intermediate:
  dir: data/intermediate
  name: processed.csv
  deserialize_kwargs:
    index_col: 0

segmented:
  dir: data/final
  name: segmented.csv
  deserialize_kwargs:
    index: false

